### ISSUE TITLE
práctica 

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/practica-architect-Nayee123#1]
[Practica_architect_Nayeli_Anai_Gonzàlez_Lopez.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Nayee123/files/7172996/Practica_architect_Nayeli_Anai_Gonzalez_Lopez.pdf)

**Comment by Lissete7** [comment]
Calificacion: 20/20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
